//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatoMaipo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public decimal IDCONTRATO { get; set; }
        public System.DateTime FECHACREACION { get; set; }
        public System.DateTime FECHATERMINO { get; set; }
        public decimal PORCCOMISION { get; set; }
        public short VIGENTE { get; set; }
        public decimal IDPRODUCTOR { get; set; }
    
        public virtual PRODUCTOR PRODUCTOR { get; set; }
    }
}
