//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatoMaipo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOVENTA
    {
        public decimal IDDOCUMENTO { get; set; }
        public Nullable<System.DateTime> FECHAEMISION { get; set; }
        public Nullable<decimal> PRECIOPRODUCTO { get; set; }
        public Nullable<decimal> PRECIOTRANSPORTE { get; set; }
        public Nullable<decimal> IMPUESTO { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public decimal IDPEDIDO { get; set; }
        public decimal IDESTADODOC { get; set; }
    
        public virtual ESTADODOCUMENTO ESTADODOCUMENTO { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
