//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatoMaipo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCUESTA
    {
        public decimal IDENCUESTA { get; set; }
        public string NOMBREREAL { get; set; }
        public string CORREO { get; set; }
        public decimal TELEFONO { get; set; }
        public string VARIEDADCATALOGO { get; set; }
        public string PROCESOSOLICITUD { get; set; }
        public string TIEMPOENVIO { get; set; }
        public string SATISFACCIONPRODUCTO { get; set; }
        public string PROCESOPAGO { get; set; }
        public decimal IDPEDIDO { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
