//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatoMaipo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFERTAPRODUCTO
    {
        public decimal IDOFERTA { get; set; }
        public decimal PRECIOUSD { get; set; }
        public decimal PRECIOCLP { get; set; }
        public string SELECCIONADO { get; set; }
        public decimal IDPRODUCTOR { get; set; }
        public decimal IDPRODUCTO { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PRODUCTOR PRODUCTOR { get; set; }
    }
}
