//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatoMaipo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public PEDIDO()
        {
            this.DETALLEPEDIDO = new HashSet<DETALLEPEDIDO>();
            this.SUBASTA = new HashSet<SUBASTA>();
            this.PARTICIPACION = new HashSet<PARTICIPACION>();
            this.DOCUMENTOVENTA = new HashSet<DOCUMENTOVENTA>();
        }
    
        public decimal IDPEDIDO { get; set; }
        public System.DateTime FECHAPEDIDO { get; set; }
        public Nullable<System.DateTime> FECHAENTREGA { get; set; }
        public string DIRECCIONPEDIDO { get; set; }
        public decimal IDCLIENTE { get; set; }
        public decimal IDESTADOPEDIDO { get; set; }
        public string CIUDAD { get; set; }
        public string PAIS { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ESTADOPEDIDO ESTADOPEDIDO { get; set; }
        public virtual ICollection<DETALLEPEDIDO> DETALLEPEDIDO { get; set; }
        public virtual ICollection<SUBASTA> SUBASTA { get; set; }
        public virtual ICollection<PARTICIPACION> PARTICIPACION { get; set; }
        public virtual ICollection<DOCUMENTOVENTA> DOCUMENTOVENTA { get; set; }
    }
}
