//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatoMaipo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DETALLEPEDIDO = new HashSet<DETALLEPEDIDO>();
            this.OFERTAPRODUCTO = new HashSet<OFERTAPRODUCTO>();
            this.PRODUCCION = new HashSet<PRODUCCION>();
        }
    
        public decimal IDPRODUCTO { get; set; }
        public string NOMBREPRODUCTO { get; set; }
        public decimal PRECIOESTIMADO { get; set; }
        public string IMAGENPRODUCTO { get; set; }
        public string BANNERPRODUCTO { get; set; }
    
        public virtual ICollection<DETALLEPEDIDO> DETALLEPEDIDO { get; set; }
        public virtual ICollection<OFERTAPRODUCTO> OFERTAPRODUCTO { get; set; }
        public virtual ICollection<PRODUCCION> PRODUCCION { get; set; }
    }
}
