//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatoMaipo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBASTA
    {
        public SUBASTA()
        {
            this.OFERTASUBASTA = new HashSet<OFERTASUBASTA>();
        }
    
        public decimal IDSUBASTA { get; set; }
        public System.DateTime FECHAINICIO { get; set; }
        public System.DateTime FECHATERMINO { get; set; }
        public decimal IDPEDIDO { get; set; }
        public decimal IDESTADOSUBASTA { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual ESTADOSUBASTA ESTADOSUBASTA { get; set; }
        public virtual ICollection<OFERTASUBASTA> OFERTASUBASTA { get; set; }
    }
}
