//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatoMaipo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOTRANSPORTE
    {
        public TIPOTRANSPORTE()
        {
            this.OFERTASUBASTA = new HashSet<OFERTASUBASTA>();
        }
    
        public decimal IDTIPO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<OFERTASUBASTA> OFERTASUBASTA { get; set; }
    }
}
