//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatoMaipo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTISTA
    {
        public TRANSPORTISTA()
        {
            this.OFERTASUBASTA = new HashSet<OFERTASUBASTA>();
        }
    
        public decimal IDTTRANSPORTISTA { get; set; }
        public string NOMBRETRANSPORTISTA { get; set; }
        public string DIRECCIONTRANSPORTISTA { get; set; }
        public string TELEFONOTRANSPORTISTA { get; set; }
        public decimal IDUSUARIO { get; set; }
        public string CORREO { get; set; }
    
        public virtual ICollection<OFERTASUBASTA> OFERTASUBASTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
