//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatoMaipo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.PRODUCTOR = new HashSet<PRODUCTOR>();
            this.TRANSPORTISTA = new HashSet<TRANSPORTISTA>();
        }
    
        public decimal ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string CONTRASENIA { get; set; }
        public string IS_HABILITADO { get; set; }
        public decimal ID_ROL { get; set; }
        public string TOKEN { get; set; }
    
        public virtual ROL ROL { get; set; }
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual ICollection<PRODUCTOR> PRODUCTOR { get; set; }
        public virtual ICollection<TRANSPORTISTA> TRANSPORTISTA { get; set; }
    }
}
